[package]
name = "p2p_chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.5.4"
reqwest = "0.11.20"
tokio = {version = "1.32.0", features = ["full"]}
